---
- hosts: localhost
  vars:
    packages:
      - arandr
      - pavucontrol
      - mate-terminal
      - vim-gtk
  tasks:
    - name: install packages
      apt:
        update_cache=yes
        cache_valid_time=3600
        name={{ item }}
        state=present
        install_recommends=no
      with_items: packages     
